### ISSUE TITLE
Results Pane - Create Pinia store

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-web#105]
# Requirements

- Create a pinia store called `resultsStore.ts`
- for state, this should have an array of `results` objects and an `activeResult` that is a `facilityId` int.
- an action for fetching results
  - this should filter the default fake results set by on `facilityName` and/or `location`
- an action for setting the active result `activeResult`
- an action for clearing the active result
- the default state should be empty and the `fetchResults` method should populate it with the default fake results list.

**Comment by Tch4lla** [comment]
Awesome sauce. I'm working with the results objects. What kind of properties would they have ? I'd like to get some dummy data just to test the store and actions

**Comment by Tch4lla** [comment]
@ermish Lets check my latest push and let me know how I can improve it when you get some time
