### ISSUE TITLE
Fix Tailwind

### ISSUE THREAD

**Issue by ann-kilzer** [ourjapanlife/findadoc-web#120]
# Requirements
---

Tailwind is not working... the colors and css styling are not visible in the site.

---
# Dependencies

- None (

**Comment by ermish** [comment]
I just pulled latest and the site appears to be rendering fine



![Image](https://user-images.githubusercontent.com/4411499/209335202-fce7ab72-90c2-4df3-b58d-900d42669ded.png)

**Comment by ermish** [comment]
I ran `yarn` then `yarn start`

**Comment by ermish** [comment]
Reopening! This happened to me when using `yarn dev` instead of `yarn start`
