### ISSUE TITLE
use i18n strings

### ISSUE THREAD

**Issue by ann-kilzer** [ourjapanlife/findadoc-web#154]
# Requirements

- [ ] Set an eslint rule to prevent raw text. This might help identify all the raw text areas to update.
- [ ] Switch all raw text to i18n strings
    - Example: `<div> hello there </div>` becomes `<div> $t('hello_message')`. This will `hello_message` string will be in the `i18n` folder. 
    - guideline: be more descriptive with the text keys. instead of `banner`, do `topnavBannerWelcomeMessage`
- [ ] Update the i18n enum and toggle to be localized properly. 
    Right now, we support `en-us` and `ja-jp`

# Dependencies

- #60

**Comment by ermish** [comment]
Overall, I think this is done. closing this for now. @theyokohamalife if I missed something, how about we make specific tickets for any areas I might have missed
