### ISSUE TITLE
[Bug] Vue/Types error

### ISSUE THREAD

**Issue by Tch4lla** [ourjapanlife/findadoc-web#167]
# Requirements
In the typescript config file, I receive an error stating 
![image](https://user-images.githubusercontent.com/99618731/214584026-f0601d92-0d90-4fde-a0a8-4467a78a8078.png)

- [ ] Fix `Vue/types` in `tsconfig.json` file under `types`  

# Dependencies

- None

**Comment by NabbeunNabi** [comment]
Does this still happen? I haven't seen this warning? How do I reproduce this if it does so I could fix it?

**Comment by theyokohamalife** [comment]
I think this may have been fixed in https://github.com/ourjapanlife/findadoc-web/pull/296 when @ermish reworked eslint. Closing this for now.
