### ISSUE TITLE
SearchResultDetails -  consistent modal sizing across screen sizes

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-web#213]
# Context

The modal is overlapping/out of the window when the height is too narrow! 

# Requirements
- [x] The model should fit all the content
- [x] The results should be clickable while the modal is open (might require making the results list height reduced when the modal is open
- [ ] (optional) you can see the map pin 📍 when the modal is open to help the user associate the results with the location. I think this will take more work though and probably a separate issue

# Dependencies

- None (Add any issue dependencies here)

**Comment by dominiksakic** [comment]
@ermish Regarding the wording of the issue: 
"The modal sizing messes up when map expands and **pushes** the footer offscreen. You can see when resizing the screen extra wide."

Do you mean the the modal overlaps with the footer? 
Me and Matt cannot reproduce the issue as you stated. 



![Image](https://github.com/ourjapanlife/findadoc-web/assets/142134892/b00ed1c7-bdef-4a96-b337-971cefe9deed)

**Comment by ermish** [comment]
> @ermish Regarding the wording of the issue: 
> "The modal sizing messes up when map expands and **pushes** the footer offscreen. You can see when resizing the screen extra wide."
> 
> Do you mean the the modal overlaps with the footer? 
> Me and Matt cannot reproduce the issue as you stated. 
> 
> 
> 
> ![Image](https://github.com/ourjapanlife/findadoc-web/assets/142134892/b00ed1c7-bdef-4a96-b337-971cefe9deed)
> 
> 

Ah good question, the experience changed since I wrote the issue description. Now the results are static. Do you want to update the issue description for us? 

## New reqs
- The model should fit all the content 
- The results should be clickable while the modal is open (might require making the results list height reduced when the modal is open 
- (optional) you can see the map pin 📍 when the modal is open to help the user associate the results with the location. I think this will take more work though and probably a separate issue

**Comment by dominiksakic** [comment]
Description updated!
