### ISSUE TITLE
Upgrade fixes: Several eslint rules are deprecated

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-web#215]
# context

After upgrading eslint, several of our eslint rules names are deprecated. (pretty much just changing the name of the rule)

<img width="522" alt="Screenshot 2023-02-20 at 2 45 56 PM" src="https://user-images.githubusercontent.com/4411499/220019534-7813173d-2f0e-4383-8be0-59aaa469093d.png">

# Requirements

- [ ] run `yarn lint` to see the warnings
- [ ] Fix them! 

# Dependencies

- None (Add any issue dependencies here)

**Comment by theyokohamalife** [comment]
Pretty sure this was resolved with #379
