### ISSUE TITLE
Create Admin Panel - Admin View - Approved Submissions

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-web#31]
## Requirements

- Ability to moderate approved submissions
    - Edit
    - Delete
    - Revert to pending

## Workflow

- Admin logs in
- Admin chooses approved submissions
- Admin can delete an inappropriate submission
    - A reason for deleting the submission must be entered in a text box
- Admin can edit incorrect or missing information
- Admin can save the changes
    - The changes will immediately go live on the site
- Admin can revert an approved submission to a pending one for further review
- Admin logs out

**Comment by theyokohamalife** [comment]
@ermish We'll need wireframes for the admin panel before we begin coding it. We should include those wireframes in the issue description.

**Comment by ermish** [comment]
> @ermish We'll need wireframes for the admin panel before we begin coding it. We should include those wireframes in the issue description.

Agreed! Just creating tickets based on our notion notes to make some progress. 
No active work yet 👍
