### ISSUE TITLE
Create Admin Panel - Moderator View

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-web#35]
# Requirements
- Page provides a clear indicator that they are a moderator. 
- Functions the same as admin view, but a few features are removed
  - Adding and Removing Moderators sections are Removed

## Workflow

- user logs into the admin dashboard
- confirms they are moderator level access
- Reviews and updates submissions

**Comment by ann-kilzer** [comment]
Would love to consider if there is anything we can leverage for admin tools such as AppSmith community edition: https://www.appsmith.com/pricing#plan-comparision

Building two UIs is going to take a lot of time and that is something we are short on
