### ISSUE TITLE
Create Search Page - Search Results Components - Desktop View

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-web#37]
# Requirements

- A list that shows healthcare professionals
- use dummy data for milestone 1
- match styling from prototype

## Workflow - Using the results list

- User can see results list and it renders properly in desktop mode

Edit: updated after developer meeting to reflect new requirements

**Comment by ann-kilzer** [comment]
Let's adjust the workflow requirements based on our meeting notes as Search is going to be very simple for Milestone 1, and Maps may not come until Milestone 4.

https://www.notion.so/ourjapanlife/2022-12-22-Developer-Meeting-4e292f36d4304cd8ae07973abc453c26
