### ISSUE TITLE
Add tests for Pinia stores

### ISSUE THREAD

**Issue by theyokohamalife** [ourjapanlife/findadoc-web#395]
We need additional tests written in order to improve the code quality of the repo. Below is a list of Pinia stores that need to be tested. Each one should be addressed in a separate PR, so please comment below with which one you'd like to work on as well as a link to your PR when it's in progress.

[Example tests](https://github.com/ourjapanlife/findadoc-web/blob/main/test/functional/modalStore.spec.ts)

- [x] loadingStore
- [x] localStore
- [ ] locationStore
- [ ] menuStore
- [ ] searchResultsStore
- [ ] specialtiesStore
- [ ] submissionStore

Be sure to include `Part of #395` at the top of your PR description.

**Comment by Anissa3005** [comment]
I will start working on the tests for localStore!

**Comment by Diego-Bittencourt** [comment]
I'll start working on the locationStore :)
