### ISSUE TITLE
Implement Conventional Commits

### ISSUE THREAD

**Issue by theyokohamalife** [ourjapanlife/findadoc-web#41]
We should implement conventional commits in our CI/CD to help keep contributions more organized and uniform. Doing so will also allow us to automate semantic versioning for future releases.

https://www.conventionalcommits.org/en/v1.0.0/

**Comment by ermish** [comment]
I want to talk through this one a bit. I've got some concerns around their implementation of the concept

**Comment by theyokohamalife** [comment]
@ermish Sure! Can we start a thread for it on Slack since it's hard for us to meet up during the week?

**Comment by ermish** [comment]
actually, let's just try it as is. 👍  
I love their concept of organizing types of commits and the ability to auto-generate changelogs. 
My concern was just around the specific naming like `feat`, `chore`, etc. which is completely different  what I'm used to and most of my workplaces use.

**Comment by ermish** [comment]
@theyokohamalife do you have any tool in mind that will generate a changelog based on conventional commits?

**Comment by ann-kilzer** [comment]
I find this a bit cumbersome and better suited to larger software projects. However, if you feel that you want to do this, let's configure husky or another tool so that we guide users to the correct formatting (might require setting up a rule on push)

**Comment by theyokohamalife** [comment]
> I find this a bit cumbersome and better suited to larger software projects. However, if you feel that you want to do this, let's configure husky or another tool so that we guide users to the correct formatting (might require setting up a rule on push)

@ann-kilzer  Since you're more familiar with husky could you create an issue to add the conventional commit formatting to it?
