### ISSUE TITLE
Add a no results indicator

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-web#416]
# Requirements

When a user refines a search that has 0 search results, we should show a nice indicator that no results were returned. 

For extra credit, if we can provide an alternative search option like clearing filters!

- [ ] Add an indicator
- [ ] Ensure it only shows on empty searches
- [ ] Test on desktop and mobile

# Dependencies

- None (Add any issue dependencies here)

**Comment by Tch4lla** [comment]
I'd like to work on this

**Comment by Ntlja** [comment]
@Tch4lla There's a design for this now! 

You can head here to check it out: 
https://www.figma.com/file/QXQxlw4jNFIhMxkKU7bbwq/Find-a-doc%2C-Japan?type=design&node-id=1611%3A23460&mode=design&t=JjQYHq4oislbgc5Z-1

I've mocked it up as a full page (and cleaned up the design), but you can just focus on the illustration and the content in the sidebar. I'll try to attach the image here! (Never used this space before, so I'm not sure how it works...)

There should be a png and svg, so you can have a look at what works better or at all lol. The png is double the size to make sure it's crisp. Ping me on Slack if you need anything else! :-)

<img width="120" alt="No-search-results-graphic" src="https://github.com/ourjapanlife/findadoc-web/assets/39023563/fb699628-c0fc-430e-bc1b-0192ffb4ed9f">
![No-search-results-graphic](https://github.com/ourjapanlife/findadoc-web/assets/39023563/3ec6841a-afa4-4fad-a35e-ccf40b1e9829)

**Comment by Ntlja** [comment]
[no-search-result-images.zip](https://github.com/ourjapanlife/findadoc-web/files/14961356/no-search-result-images.zip)
