### ISSUE TITLE
[bug] update google maps marker

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-web#417]
# Requirements

Google Maps is updating from `Marker` to `google.maps.marker.AdvancedMarkerElement` We need to upgrade this. 

> js?callback=__google…places&v=weekly:233 As of February 21st, 2024, google.maps.Marker is deprecated. Please use google.maps.marker.AdvancedMarkerElement instead. At this time, google.maps.Marker is not scheduled to be discontinued, but google.maps.marker.AdvancedMarkerElement is recommended over google.maps.Marker. While google.maps.Marker will continue to receive bug fixes for any major regressions, existing bugs in google.maps.Marker will not be addressed. At least 12 months notice will be given before support is discontinued. Please see https://developers.google.com/maps/deprecations for additional details and https://developers.google.com/maps/documentation/javascript/advanced-markers/migration for the migration guide.

- [ ] Follow the directions in the link provided and upgrade it. 

# Dependencies

- None (Add any issue dependencies here)

**Comment by ermish** [comment]
@theyokohamalife  might be a good one for you?

**Comment by theyokohamalife** [comment]
@ermish  I'll take a look at it!

**Comment by ermish** [comment]
as part of #468 this error goes away with the custom marker. The custom marker is easier to work with for svgs, and was surprisingly simpler code.
