### ISSUE TITLE
Set up linting rules and pipeline

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-web#42]
# requirements 

- Linting rules are updated based on team's spec. 
- linter is ran on PRs. 
- All files in project have been linted and updated

**Comment by ann-kilzer** [comment]
Is this a duplicate of #20

**Comment by ermish** [comment]
@ann-kilzer separate. One is for running our test suite and the other is for running our linters

**Comment by ann-kilzer** [comment]
I misread 😆
