### ISSUE TITLE
Disable prettier from changing file formatting

### ISSUE THREAD

**Issue by NabbeunNabi** [ourjapanlife/findadoc-web#433]
# Requirements

- [ ] Create a `prettierignore ` file that disables prettier in all files to ignore semicolons being added or reformatting of files by all contributors who use prettier, so as to not have to go back and reformat files in a PR or file.

# Dependencies

- None

**Comment by ermish** [comment]
pro tip for writing issues, start with the problem statement first before listing out the requirements.  

why do we want to disable prettier?

**Comment by NabbeunNabi** [comment]
Updated! I hope that is clearer

**Comment by ermish** [comment]
> Updated! I hope that is clearer

Stellar ⭐
