### ISSUE TITLE
[bug] Icons not rendering on prod

### ISSUE THREAD

**Issue by theyokohamalife** [ourjapanlife/findadoc-web#441]
Icons are currently not rendering on prod for the site logo, healthcare professionals, and languages.

![Image](https://github.com/ourjapanlife/findadoc-web/assets/31802656/b86be3fb-1dcf-4b94-be44-2a8711808662)

**Comment by theyokohamalife** [comment]
We'll tackle this on Wednesday in a group coding session.

**Comment by NabbeunNabi** [comment]
I was wondering @ermish and @theyokohamalife if you have looked at this and think it is a good add to the project, [vue-svg-loader](https://www.npmjs.com/package/vue-svg-loader )? 

## Pros

1. Imports SVG as components so looks clean in the code.
2.  Has very few dependencies. Only 2

## Cons

1. Has dependencies so it does add more to the project

**Comment by ermish** [comment]
> I was wondering @ermish and @theyokohamalife if you have looked at this and think it is a good add to the project, [vue-svg-loader](https://www.npmjs.com/package/vue-svg-loader)?
> 
> ## Pros
> 1. Imports SVG as components so looks clean in the code.
> 2. Has very few dependencies. Only 2
> 
> ## Cons
> 1. Has dependencies so it does add more to the project

a best practice is to have all images (including svg's) to be cacheable which means they should not be inlined. Unfortunately `vue-svg-loader` inlines them, so it's not a valid option

**Comment by NabbeunNabi** [comment]
But as mentioned yesterday it seems like the way we did it on the  about us page fits the requirements for svgs and makes it cacheable so we should proceed that way?

**Comment by ermish** [comment]
> But as mentioned yesterday it seems like the way we did it on the about us page fits the requirements for svgs and makes it cacheable so we should proceed that way?

yeah, that should be fine. Just documenting the thoughts for anyone else reading this. 👍

**Comment by ermish** [comment]
I'll have a PR ready for this soon 🔥
