### ISSUE TITLE
[bug] 500 error on Safari

### ISSUE THREAD

**Issue by theyokohamalife** [ourjapanlife/findadoc-web#443]
# Problem
The front page is showing a 500 error when loaded on Safari:

`Invalid regular expression: invalid group specifier name`

# Success
The front page is able to render without displaying an error.

# Implementation notes
It may have something to do with the way we're loading images.

![Image](https://github.com/ourjapanlife/findadoc-web/assets/31802656/d3ac5f34-fea7-4e90-9acf-a2de5044fd4f)

**Comment by theyokohamalife** [comment]
LaShawn and @NabbeunNabi will look at this tonight.

**Comment by NabbeunNabi** [comment]
Hi @theyokohamalife. You said this error went away and fixed itself? Should this issue be closed?

**Comment by NabbeunNabi** [comment]
I think this error is gone and with the typescript all implemented it can be closed. Haven't seen this in months
