### ISSUE TITLE
Add a Navigation Link for Moderation Panel

### ISSUE THREAD

**Issue by NabbeunNabi** [ourjapanlife/findadoc-web#450]
# Problem
We need a link in the `NavBar` for Moderators to go to the login page in order to log into the Moderation Panel.

# Success
There is a link with the proper styling that matches what is currently on the website for links. This link should have the functionality to go to the Login Page
### Requirements

- [ ] Add a link that appears on the `Navbar`
- [ ] The link seamlessly fits into the other links in the navbar
- [ ] It successfully redirects to the Login Page.

# Implementation notes
Whoever takes this ticket. You got it!

**Comment by MohitKambli** [comment]
Hello,
Hope you're doing well.
I would like to work on this issue.

Thanks and Regards,
Mohit Kambli

**Comment by MohitKambli** [comment]
Hello,
As per the request, I have added a link named "Login" in the TopNav component.
So, for now, the page looks something like this:

![image](https://github.com/ourjapanlife/findadoc-web/assets/31406633/06f1f240-cc77-4a54-8f3e-64d9b19261a6)

Once the Login link has been clicked, the login page opens up as required.
This is how that part looks:

![image](https://github.com/ourjapanlife/findadoc-web/assets/31406633/53cddf07-c66e-47e4-8efc-c86955d19742)


If at all I misunderstood something or implemented anything incorrectly, then do let me know.
Sincere apologies for the same.

Thanks and Regards,
Mohit Kambli

**Comment by NabbeunNabi** [comment]
Hello @MohitKambli, Sorry for the late response and thanks for working on this. If you would like to work together sometime on creating a PR with this so that it can go through proper code review let me know.

**Comment by NabbeunNabi** [comment]
Blocked by #542

**Comment by NabbeunNabi** [comment]
This was resolved once you are logged in through the auth. It appears on the navbar
