### ISSUE TITLE
`Submission List Item Component` for Moderation Panel

### ISSUE THREAD

**Issue by NabbeunNabi** [ourjapanlife/findadoc-web#452]
# Problem
There is no component that can take in the data from the database that will display the data required

# Success
This component can take in props that are displayed as shown on [Figma](https://www.figma.com/file/QXQxlw4jNFIhMxkKU7bbwq/Find-a-doc%2C-Japan?type=design&node-id=1621-17300&mode=design&t=YlT64bYAuVCI537V-4 ).

![Image](https://github.com/ourjapanlife/findadoc-web/assets/124335161/f80f1488-2722-497f-b956-af5794bae4fd)

![Image](https://github.com/ourjapanlife/findadoc-web/assets/124335161/c35f2bc1-2ee8-4aa3-bf2a-f11f9bac6943)

- @ermish suggested that since we do not have access to the facility name at the moment that the facility name in this component should show the `submissionId`

Should be just a singular line of this whole image. That can be reused in a loop.

### Requirements

- [ ] The component should display a `number`. `status`, `modified`, `submitted`
- [ ] Matches Figma
- [ ] Accepts props to be used with provided data

# Implementation notes
Currently the backend does not provide a status. So this might have to be hardcoded when first accepting the props when data has been fetched

**Comment by theyokohamalife** [comment]
@NabbeunNabi Could you include a screenshot of the component to give devs a bit more context?

**Comment by NabbeunNabi** [comment]
Will go through and add screen shots shortly to all the ones that don't have any
