### ISSUE TITLE
Create a top bar for Moderation Panel

### ISSUE THREAD

**Issue by ProgressChris88** [ourjapanlife/findadoc-web#453]
![image](https://github.com/ourjapanlife/findadoc-web/assets/117893544/6f7c9b68-ce72-4454-9d70-0e8852829d12)

# Problem
Currently need a top bar in the portal facility. Issue #454 is now part of this.

# Success
This currently just needs the UI/UX that displays `For Review`, `Aprroved`, or `Rejected` based on the local state that is clicked is clicked on the sideBar as seen here

![Image](https://github.com/ourjapanlife/findadoc-web/assets/124335161/ed3c4e00-416b-415d-9a91-eefd6a1c4083)

# Implementation notes
<a href="https://www.figma.com/file/QXQxlw4jNFIhMxkKU7bbwq/Find-a-doc%2C-Japan?type=design&node-id=1621%3A10418&mode=design&t=Uosf0ToCpsqDtt1Z-1">Figma Page</a>

**Comment by theyokohamalife** [comment]
@ProgressChris88 Let's update this with a screenshot when you have time 🙏

**Comment by Anissa3005** [comment]
@theyokohamalife @NabbeunNabi Is this not already implemented? Since the sidebar and topbar are already included in the version now?
