### ISSUE TITLE
Add search box to top bar component of the moderation panel

### ISSUE THREAD

**Issue by ShizuokaTerrier** [ourjapanlife/findadoc-web#454]
# Problem 

Not a problem as such. We need to make it! 

This is blocked by https://github.com/ourjapanlife/findadoc-web/issues/453, because we need the top bar component created first.

# Success

When it exists. 

# Requirements 

- [ ] Created search box. 
- [ ] Styled to match figma design.  

# Implementation notes

[Link for the figma](https://www.figma.com/file/QXQxlw4jNFIhMxkKU7bbwq/Find-a-doc%2C-Japan?type=design&node-id=1621%3A10418&mode=design&t=RwCbWFAg3Ob0dSEp-1)

<img width="1353" alt="image" src="https://github.com/ourjapanlife/findadoc-web/assets/151515133/7ccf881b-72b9-4006-91f7-9a1280627eac">

**Comment by theyokohamalife** [comment]
Hey, @ShizuokaTerrier! Could you update this ticket to include a screenshot of the component in the description?
