### ISSUE TITLE
Create the `SubmissionList` component for Moderation Panel

### ISSUE THREAD

**Issue by NabbeunNabi** [ourjapanlife/findadoc-web#455]
# Problem
There isn't a list component that shows the requested submissions. This should use the component from issue #452 to list the submissions.

# Success
Be able use the fetched data from the API and then display the data using the component listed above. Should have styling matching [Figma](https://www.figma.com/file/QXQxlw4jNFIhMxkKU7bbwq/Find-a-doc%2C-Japan?type=design&node-id=1621-17300&mode=design&t=YlT64bYAuVCI537V-4 )

![Image](https://github.com/ourjapanlife/findadoc-web/assets/124335161/a5d28ebe-2bb4-4fb9-bd96-3576f46b1b44)

This uses the component from #452  and maps through them to show the whole list

One of this 
### Requirements

- [ ] Able to pass props to the following component
- [ ] Show the List of Submissions

# Implementation notes
Currently the `Status` is not implemented so we need to put filler data for now in order to wait for the backend

**Comment by theyokohamalife** [comment]
@NabbeunNabi Let's update this with a screenshot when you have time. 🙏
