### ISSUE TITLE
Navbar - Add Home Button to page

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-web#50]
# Requirements 

- Add Home button to the navbar
- Add logo image to the codebase
- Update css to match wireframe

## Wireframe to reference for top-left button positioning

![Untitled](https://user-images.githubusercontent.com/4411499/196034073-45574f1b-1d1a-435c-b1c1-7f66ce526590.png)

**Comment by lucy-gelderloos** [comment]
Hello, could I be assigned this issue?
