### ISSUE TITLE
Implement Vee-validate on `editSubmissionForm`

### ISSUE THREAD

**Issue by NabbeunNabi** [ourjapanlife/findadoc-web#507]
# Problem
We are trying to figure out the best way to implement form validation. Nuxt has a module

## Linked Issues
#502 
#460 

# Success
Validates using [Vee-validate](https://nuxt.com/modules/vee-validate ).

### Requirements

- [ ] Takes the basic validation if implemented from issue #460 and takes it to another level

# Implementation notes
Follow the documentation

**Comment by Anissa3005** [comment]
@NabbeunNabi This issue can be closed since we are at the moment using our own validation logic.
