### ISSUE TITLE
Implement the correct count in the `ModDashboardLeftNavbar`

### ISSUE THREAD

**Issue by NabbeunNabi** [ourjapanlife/findadoc-web#509]
# Problem
Right now the left navbar is hardcoded at 0. 

![Image](https://github.com/ourjapanlife/findadoc-web/assets/124335161/3914d737-7f73-4dff-812b-4608c6f73f45)

# Success
It should show the correct number for each choice based on the data fetched. 
### Requirements

- [ ] Get the data from the store and show the count

# Implementation notes
Along with issue #508  a lot of this logic could be handled in the store. Then called in the components

**Comment by theyokohamalife** [comment]
@NabbeunNabi Has this ticket been started yet? Would you like some help with it?

**Comment by NabbeunNabi** [comment]
> @NabbeunNabi Has this ticket been started yet? Would you like some help with it?

I was going to let Tam pair with me or work on it. But I can implement it this week.
