### ISSUE TITLE
Navbar - Implement routing for Home Button

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-web#52]
# Requirements

- We use vue router for going between pages. We need to enable routing for the home button
- It should not show a `/` in the URL when clicked.

**Comment by ermish** [comment]
This has a dependency on #50

**Comment by theyokohamalife** [comment]
@ermish Since we're using Nuxt, shouldn't we use `NuxtLink` instead? https://nuxtjs.org/docs/get-started/routing/

**Comment by AidanFournier** [comment]
I can take on this issue!

**Comment by ann-kilzer** [comment]
Looks like this is fixed
