### ISSUE TITLE
Navbar - Implement CSS for About Us link

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-web#53]
# Requirements 

- The About us Page should be positioned and styled matching the wireframe below
-  Page and Link should be responsive 

## Wireframe reference

![Untitled](https://user-images.githubusercontent.com/4411499/196034294-558ad2ad-9656-49ae-b8c6-3a6ad494bde2.png)

**Comment by theyokohamalife** [comment]
For anyone interested in working on this issue, just wanted to note that the wireframe about isn't specifically for the About Us page. We would like a link added to the nav bar that says `About Us` and a very simple page created with that as the title.

**Comment by ann-kilzer** [comment]
We're looking for work about padding / margins and gridding, not so much font or other design choices

**Comment by Kumaguro3** [comment]
Hi guys ! Just to make sure I understand everything as this is my very first collaboration: 
- So basically, I just need to style the About Us link in the Nav Bar ? Or do I also style the entire About Us page according to the picture style? 
- Can I decide the padding/margin as long it kinda looks like the picture or do you have specific numbers to follow ?

**Comment by Kumaguro3** [comment]
Thanks Ann and well-noted :)
