### ISSUE TITLE
BUG: missing translations  in mod panel

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-web#537]
# Problem
We're getting some errors for missing translations. Fix em!

![image](https://github.com/ourjapanlife/findadoc-web/assets/4411499/209fa698-82db-425e-b335-469c3cdb94e3)

**Comment by NabbeunNabi** [comment]
This links to and is solved within #510

**Comment by NabbeunNabi** [comment]
Was fixed when fetching real data. Just have to be more strict in the future to not have strict no raw string rules.
