### ISSUE TITLE
Navbar - Add Hamburger Menu Icon

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-web#54]
# Requirements

- Add hamburger menu icon to codebase
- Hamburger menu should appear when the site is viewed in `portrait` mode
- Hamburger menu should appear when the site is viewed in `landscape` mode and the width is less than `800px`. 
- The css should follow [tailwind css](http://tailwindcss.com/) best practices.
- This should be implemented in the `TopNav` vue component

- The actual hamburger menu will be added in a separate PR

**Comment by Tch4lla** [comment]
Please add me to this issue as well
