### ISSUE TITLE
FEAT: add nuxt support to our typescript config

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-web#541]
# Problem
- importing Nuxt modules aren't working 
- `$t()` for our translations show as an error. This can be fixed with nuxt support. 

# Success

- consider if we should extend from Nuxt config or if we can add only the parts we need. 
  - **Concern:** Nuxt has a bunch of other stuff it comes with in the config. We need to determine if we want everything or this conflicts with what we have set up today.

**Comment by NabbeunNabi** [comment]
Completed per #566
