### ISSUE TITLE
Navbar - Wire up the hamburger menu logic

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-web#55]
# Requirements

- Make hamburger menu clickable
- The css should follow [tailwind css](http://tailwindcss.com/) best practices.
- Add a visual css indicator that it has been clicked
- Through vue best practices, this should trigger showing the hamburger menu and update the `state` in the navbar vue component.
- Note: the hamburger menu itself will be created in a separate PR.

This has a dependency on PR #54

**Comment by Tch4lla** [comment]
Please add me to this issue
