### ISSUE TITLE
Navbar - Create Hamburger Menu Component

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-web#56]
# Requirements

- Create a separate hamburger menu vue component and add it into the `TopNav` vue component.
- Implement a nice UI of your choice for the hamburger menu
- Add a css transition animation for showing and hiding the hamburger menu
- This is just the empty component creation. Links can be added in a separate PR.

----

This has a dependency on PR #54 and #55

**Comment by Tch4lla** [comment]
@ermish I would like to take on this task. May I be assigned to it?

**Comment by ermish** [comment]
it's all yours @Tch4lla!

**Comment by Tch4lla** [comment]
I am willing to take them all :)

**Comment by ermish** [comment]
can you comment on them as well saying you want to take them? Interestingly, I can't directly add you if you're not in the conversation.
