### ISSUE TITLE
Navbar - Add links and styling to hamburger menu

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-web#57]
# Requirements

- Add links that normally show in landscape mode to the hamburger menu. 
- Add a nice css styling using [tailwind css](http://tailwindcss.com/) best practices

----

This has a dependency on PR #56 

---- 
Design

- [Wireframe ](https://www.figma.com/file/QXQxlw4jNFIhMxkKU7bbwq/Find-a-doc%2C-Japan?type=design&node-id=1276%3A1561&mode=design&t=lXY8G3vAnxFyHqpq-1 )

**Comment by Kumaguro3** [comment]
Hey Philip, as I managed the first link in the navbar, I would be happy to tackle the styling of the hamburger menu. What should be inside it btw ? Also, regarding the language option in the navbar, should it be inside the hamburger or on the left/right of it ? Or it's up to me?

**Comment by ermish** [comment]
hey @Kumaguro3! I'll send you a message on slack with more details

**Comment by theyokohamalife** [comment]
The design for the hamburger menu can be viewed on [Figma](https://www.figma.com/file/QXQxlw4jNFIhMxkKU7bbwq/Find-a-doc%2C-Japan?type=design&node-id=704-12700&mode=design&t=nxtTEuXW3sg9ZiJW-0).

**Comment by theyokohamalife** [comment]
I posted on the design channel how we may want to include the footer links since the footer won't be rendered on some pages:

https://find-a-doc.slack.com/archives/C062ACS4RJA/p1716818680897639
