### ISSUE TITLE
Navbar - Create Locale Menu Dropdown

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-web#58]
# Requirements

- Create a new vue dropdown component and integrate into the `TopNav` vue component
- Using vue best practices, wire up logic for opening and closing the menu based on local vue state. 
- You can use `English` and `Japanese` as temporary, hard-coded options in the menu for this PR. 
- UI should be responsive for when page changes width and should show in the hamburger menu

**Comment by ann-kilzer** [comment]
consider https://vuejsexamples.com/tag/dropdown/ as ideas. No need to wire to any data yet
