### ISSUE TITLE
Fix top nav element spacing

### ISSUE THREAD

**Issue by theyokohamalife** [ourjapanlife/findadoc-web#596]
# Problem
Elements in the top nav are overlapping since adding additional languages to the locale selection dropdown. The lack of spacing to the right of the dropdown is also causing additional scrollbars to appear where there shouldn't be any.

# Success
The top nav menu items are moved slightly to the left and there is once again spacing to the right of the locale selection dropdown. Additionally, the footer is stickied at the bottom of all pages in desktop view and remains stationary while scrolling.

# Screenshots 

Before and after:
![Screenshot 2024-06-19 at 8 27 56 PM](https://github.com/ourjapanlife/findadoc-web/assets/31802656/9eb14909-d58f-445f-bc2b-9c1df5816134)

**Comment by dominiksakic** [comment]
@NabbeunNabi @theyokohamalife 
I would like to work on the issue.

**Comment by NabbeunNabi** [comment]
Looks like someone else must have fixed it since I cannot recreate the error
