### ISSUE TITLE
Navbar - Wire up locale dropdown menu

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-web#60]
# Requirements

- Connect the locale dropdown menu to the pinia state store for language. 
- Trigger an update to the store when the menu is changed
- Update the dropdown menu local state and UI to match the user's selection
- Wire to Vue i18n: https://kazupon.github.io/vue-i18n/

See https://github.com/WWCodeTokyo/speak-her-db for an example in another vue codebase

## Notes: 
- be sure to use "locale" and not "language" for variable names
- Relevant ISO codes are `en` for english and `ja` for Japanese
- Ask @ann-kilzer for questions as she has experience with i18n (internationalization)

----

This has a dependency on PR #59 and #58

**Comment by ann-kilzer** [comment]
Since I did this in v1 and have a lot of experience with locale UIs, would love to help here
