### ISSUE TITLE
BUG: Error messages displayed before filling in the submission

### ISSUE THREAD

**Issue by Anissa3005** [ourjapanlife/findadoc-web#623]
# Problem

In production when you got to `add a doctor`  the error messages are already displayed, this logic should happen after you entered wrong value or no value when filing in the form. 

![Image](https://github.com/ourjapanlife/findadoc-web/assets/114712265/4e7a414b-81f8-4ff4-883c-de2f5142c21c)

# Success
Error message only displayed when starting filling in the form and a value is missing or incorrect.
### Requirements

- [ ] Change the logic when error message is displayed

**Comment by NabbeunNabi** [comment]
On it!
