### ISSUE TITLE
Navbar - Change the route for the About page

### ISSUE THREAD

**Issue by theyokohamalife** [ourjapanlife/findadoc-web#68]
# Requirements

- Change the route from `/aboutPage` to `/about`

## Screenshot
![Screen Shot 2022-10-18 at 8 49 21 PM](https://user-images.githubusercontent.com/31802656/196421600-d07f83b4-031b-454d-bf19-c8352dd1b7ba.png)

**Comment by parush-uppal** [comment]
Hi would like to work on the issue could you please assign it

**Comment by parush-uppal** [comment]
Hi i am unable to run the project in my local machine just wanted to know after changing the route in nav component should in change the name of about component also from aboutPage to about

**Comment by ann-kilzer** [comment]
Hi @parush-uppal would you mind going through the README and getting the project up and running before continuing with tickets? If you find any issues please feel free make suggestions to the README, or ask in the slack channel. Thanks

**Comment by kappanjoe** [comment]
I can take this! :)

**Comment by ann-kilzer** [comment]
@kappanjoe thanks for your interest, I had privately reached out to Nasira on this one, but please check out our contributing and join our slack to hear about more opportunities
