### ISSUE TITLE
FIX: Display the correct name in submissions page

### ISSUE THREAD

**Issue by Anissa3005** [ourjapanlife/findadoc-web#703]
# Problem
Currently, the correct professional name is not being displayed when viewing submissions.

![Image](https://github.com/user-attachments/assets/8c953d11-6328-45ce-9444-4e7c83570de9)

When a user creates a submission, only the following data is accessible (for the moment):
```
input CreateSubmissionInput {
  googleMapsUrl: String
  healthcareProfessionalName: String
  spokenLanguages: [Locale!]
  notes: String
}
```

# Success
The correct name should be displayed when viewing submissions.

### Requirements

- [ ] Debug the issue to ensure the correct information is displayed.

# Implementation notes
[Suggest how this might be implemented.]

**Comment by khanSoliheen** [comment]
@Anissa3005, I'd love to work on this, but I'm unable to find where I can view or edit the submission. Currently, I can only add a doctor. That's all I can do for now. 
<img width="1440" alt="Screenshot 2024-08-19 at 06 01 19" src="https://github.com/user-attachments/assets/8351463b-f61d-43a1-9d06-065d802fe10e">
