### ISSUE TITLE
bug: eslint nuxt import issue

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-web#94]
# Requirements

- Nuxt magically imports the `defineNuxtPlugin` method in the `vue-gtag.client` component. This causes an eslint lint bug. We should add a proper import for the method. 
- Note: `nuxt` is invalid to import from.
- We can't comment this out either as the CI linter doesn't accept eslint comments.

**Comment by Tch4lla** [comment]
Let's get it !

**Comment by ann-kilzer** [comment]
@all-contributors please add @ermish  for code.
